name: blender-${dataset.scene}
tag: ""
seed: 42

diffusion:
  src_prompt:  
  tgt_prompt:  make it cactus
  guidance_scale: 350
  resolution: 128
  generation_step: 8000
  unseen_views: false
  unseen_optimization: 500
  seen_optimization: 1501
  prompt_noising_scale: 0.


phong:
  ambient: 0.1
  diffuse: 0.7
  specular: 0.2
  shininess: 32.0
  frequency: 4


dataset:
  name: blender
  scene: ficus
  root_dir: ../data/nerf_synthetic/${dataset.scene}
  img_wh:
    - 512
    - 512
  # img_downscale: 1 # specify training image size by either img_wh or img_downscale
  near_plane: 2.0
  far_plane: 6.0
  scale_test_traj: 1.0
  reverse_up: false
  train_split: "train"
  val_split: "val"
  test_split: "test"

model:
  name: neus
  radius: 1.5
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 20000
  learned_background: false
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      fusion_edit: false
      edit: false
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  geometry_edit:
    name: volume-sdf-edit
    radius: ${model.radius}
    feature_dim: 13
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      fusion_edit: false
      edit: true
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
    mlp_network_config_edit:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      fusion_edit: true
      edit: true
      sphere_init: false
      sphere_init_radius: 0.5
      weight_norm: true
  texture:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      fusion_edit: false
      edit: false
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
  texture_edit:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 1
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      fusion_edit: false
      edit: true
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: tanh

system:
  name: neus-system
  loss:
    lambda_rgb_mse: 10.
    lambda_rgb_l1: 0.
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_curvature: 0.
    lambda_sparsity: 0.0
    lambda_distortion: 0.
    lambda_opaque: 0.
    lambda_identity_normal: 0.1
    lambda_normal: 5.
    lambda_pds: 4.
    lambda_phong: 0.8
    sparsity_scale: 1.
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      texture:
        lr: 0.01
      geometry_edit:
        lr: 0.001 # used to be 0.001
      texture_edit:
        lr: 0.001
      variance:
        lr: 0.001
  warmup_steps: 500
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
      - ${system.warmup_steps}
    schedulers:
      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
        args:
          start_factor: 0.01
          end_factor: 1.0
          total_iters: ${system.warmup_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.warmup_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

export:
  chunk_size: 2097152
  export_vertex_color: True

trainer:
  max_steps: 100000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 10000
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
